features:
  - python latest

nginx:
  root: public_html
  passenger:
    enabled: "on"
    startup_file: app.py
    app_type: python
    python: .pyenv/shims/python

commands:
  - test -f requirements.txt && pip install -r $_
  - python public_html/manage.py collectstatic --noinput
  - python public_html/manage.py migrate
