# Generated by Django 5.2.1 on 2025-08-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("password", models.CharField(max_length=123)),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("login_methode", models.CharField(default="email", max_length=50)),
                ("contact_no", models.CharField(blank=True, max_length=15, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("user_schema", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
